//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightQuoteCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class fighter_details
    {
        public int id { get; set; }
        public string fighter_name { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Reach { get; set; }
        public string Stance { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
