//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FightQuoteCloud
{
    using System;
    using System.Collections.Generic;
    
    public partial class total_fight_data
    {
        public int id { get; set; }
        public string R_fighter { get; set; }
        public string B_fighter { get; set; }
        public byte R_KD { get; set; }
        public byte B_KD { get; set; }
        public string R_SIG_STR { get; set; }
        public string B_SIG_STR { get; set; }
        public string R_SIG_STR_pct { get; set; }
        public string B_SIG_STR_pct { get; set; }
        public string R_TOTAL_STR { get; set; }
        public string B_TOTAL_STR { get; set; }
        public System.TimeSpan R_TD { get; set; }
        public System.TimeSpan B_TD { get; set; }
        public string R_TD_pct { get; set; }
        public string B_TD_pct { get; set; }
        public byte R_SUB_ATT { get; set; }
        public byte B_SUB_ATT { get; set; }
        public byte R_PASS { get; set; }
        public byte B_PASS { get; set; }
        public byte R_REV { get; set; }
        public byte B_REV { get; set; }
        public string R_HEAD { get; set; }
        public string B_HEAD { get; set; }
        public string R_BODY { get; set; }
        public string B_BODY { get; set; }
        public string R_LEG { get; set; }
        public string B_LEG { get; set; }
        public string R_DISTANCE { get; set; }
        public string B_DISTANCE { get; set; }
        public string R_CLINCH { get; set; }
        public string B_CLINCH { get; set; }
        public string R_GROUND { get; set; }
        public string B_GROUND { get; set; }
        public string win_by { get; set; }
        public byte last_round { get; set; }
        public System.TimeSpan last_round_time { get; set; }
        public string Format { get; set; }
        public string Referee { get; set; }
        public System.DateTime date { get; set; }
        public string location { get; set; }
        public string Fight_type { get; set; }
        public string Winner { get; set; }
    }
}
